version: "3.7"
services:
  backend:
    build: ./backend
    command: ["sh", "/app/backend/scripts/run-prod.sh"]
    volumes:
      - backend_data:/root/uploads
    environment:
      ADMIN_USERNAME: "admin"
      ADMIN_PASSWORD: "password"
      DATABASE_URL: "mysql+pymysql://audino:audino@mysql/audino?charset=utf8mb4"
      JWT_SECRET_KEY: "secretkey"
      JWT_REDIS_STORE_URL: "redis://:audino@redis:6379/0"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - backend-network
      - frontend-network

  frontend:
    build: ./frontend
    volumes:
      - www:/app/frontend/build

  nginx:
    build: ./nginx
    volumes:
      - www:/var/www/html:ro
    ports:
      - 80:80
    depends_on:
      - backend
    networks:
      - frontend-network

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_prod_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "audino"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "audino"
      MYSQL_PASSWORD: "audino"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "audino", "-paudino"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend-network

  redis:
    build: ./redis
    volumes:
      - redis_data:/data
    environment:
      REDIS_PASSWORD: "audino"
    networks:
      - backend-network

volumes:
  mysql_prod_data:
  redis_data:
  backend_data:
  www:

networks:
  backend-network:
  frontend-network:
